name: aurora_push_example
description: Demonstrates how to use the pushed_messaging plugin.
version: 0.2.0+2
publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  pushed_messaging:
    path: ../
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^18.0.1
  flutter_local_notifications_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-community-plugins/flutter_local_notifications_aurora.git
      ref: aurora-0.5.3
  shared_preferences: ^2.3.3
  shared_preferences_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/packages.git
      path: packages/shared_preferences_aurora
      ref: aurora-shared_preferences_aurora-0.5.4 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
