name: pushed_messaging
description: A new Flutter plugin project for Aurora OS to get Push Messages.
version: 0.2.0+3
#homepage: https://pub-aurora.friflex.com/packages/pushed_messaging
homepage: https://github.com/smmarty/aurora_flutter/tree/main/packages/pushed_messaging
repository: https://github.com/smmarty/aurora_flutter/tree/main/packages/pushed_messaging
publish_to: https://pub-aurora.friflex.com

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=3.3.10"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fake_async: ^1.3.1

flutter:
  plugin:
    platforms:
      aurora:
        pluginClass: PushedMessagingPlugin
